// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Event struct {
	ID        uuid.UUID
	Name      string
	EventDate time.Time
	CreatedAt time.Time
	Location  sql.NullString
	Summary   sql.NullString
}

type EventMember struct {
	EventID   uuid.UUID
	PersonID  uuid.UUID
	Role      string
	CreatedAt time.Time
}

type Person struct {
	ID           uuid.UUID
	Name         string
	Role         sql.NullString
	CreatedAt    time.Time
	Email        sql.NullString
	PasswordHash sql.NullString
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type Task struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	OwnerID      uuid.NullUUID
	Status       string
	Priority     int32
	DueDate      sql.NullTime
	Tags         []string
	LastUpdateAt sql.NullTime
	CreatedAt    time.Time
	EventID      uuid.UUID
	Category     string
	CompletedAt  sql.NullTime
	IsArchived   bool
	DeletedAt    sql.NullTime
	AssigneeText sql.NullString
	Subtasks     pqtype.NullRawMessage
}

type TaskDependency struct {
	TaskID       uuid.UUID
	DependencyID uuid.UUID
	CreatedAt    time.Time
}

type TaskEvent struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	EventType string
	Changes   json.RawMessage
	CreatedAt time.Time
	ActorID   uuid.NullUUID
}

type TaskUpdate struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	AuthorID  uuid.NullUUID
	Note      string
	CreatedAt time.Time
}

type Template struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	CreatedAt   time.Time
}

type TemplateTask struct {
	ID              uuid.UUID
	TemplateID      uuid.UUID
	Title           string
	Description     sql.NullString
	Category        string
	Priority        int32
	RelativeDueDays sql.NullInt32
}
