// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const addEventMember = `-- name: AddEventMember :exec
INSERT INTO event_members (event_id, person_id, role)
VALUES ($1, $2, $3)
`

type AddEventMemberParams struct {
	EventID  uuid.UUID
	PersonID uuid.UUID
	Role     string
}

func (q *Queries) AddEventMember(ctx context.Context, arg AddEventMemberParams) error {
	_, err := q.db.ExecContext(ctx, addEventMember, arg.EventID, arg.PersonID, arg.Role)
	return err
}

const batchSoftDeleteTasks = `-- name: BatchSoftDeleteTasks :exec
UPDATE tasks 
SET deleted_at = NOW() 
WHERE id = ANY($1::uuid[])
`

func (q *Queries) BatchSoftDeleteTasks(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, batchSoftDeleteTasks, pq.Array(dollar_1))
	return err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (name, event_date) VALUES ($1, $2) RETURNING id, name, event_date, created_at, location, summary
`

type CreateEventParams struct {
	Name      string
	EventDate time.Time
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent, arg.Name, arg.EventDate)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.CreatedAt,
		&i.Location,
		&i.Summary,
	)
	return i, err
}

const createPerson = `-- name: CreatePerson :one
INSERT INTO people (name, email, password_hash, role)
VALUES ($1, $2, $3, 'user')
RETURNING id, name, role, created_at, email, password_hash
`

type CreatePersonParams struct {
	Name         string
	Email        sql.NullString
	PasswordHash sql.NullString
}

func (q *Queries) CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error) {
	row := q.db.QueryRowContext(ctx, createPerson, arg.Name, arg.Email, arg.PasswordHash)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    title, description, owner_id, priority, due_date, tags, event_id, category,
    assignee_text, subtasks
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) 
RETURNING id, title, description, owner_id, status, priority, due_date, tags, last_update_at, created_at, event_id, category, completed_at, is_archived, deleted_at, assignee_text, subtasks
`

type CreateTaskParams struct {
	Title        string
	Description  sql.NullString
	OwnerID      uuid.NullUUID
	Priority     int32
	DueDate      sql.NullTime
	Tags         []string
	EventID      uuid.UUID
	Category     string
	AssigneeText sql.NullString
	Subtasks     pqtype.NullRawMessage
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.Title,
		arg.Description,
		arg.OwnerID,
		arg.Priority,
		arg.DueDate,
		pq.Array(arg.Tags),
		arg.EventID,
		arg.Category,
		arg.AssigneeText,
		arg.Subtasks,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		pq.Array(&i.Tags),
		&i.LastUpdateAt,
		&i.CreatedAt,
		&i.EventID,
		&i.Category,
		&i.CompletedAt,
		&i.IsArchived,
		&i.DeletedAt,
		&i.AssigneeText,
		&i.Subtasks,
	)
	return i, err
}

const createTaskEvent = `-- name: CreateTaskEvent :exec
INSERT INTO task_events (task_id, event_type, changes)
VALUES ($1, $2, $3)
`

type CreateTaskEventParams struct {
	TaskID    uuid.UUID
	EventType string
	Changes   json.RawMessage
}

func (q *Queries) CreateTaskEvent(ctx context.Context, arg CreateTaskEventParams) error {
	_, err := q.db.ExecContext(ctx, createTaskEvent, arg.TaskID, arg.EventType, arg.Changes)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, name, event_date, created_at, location, summary FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.CreatedAt,
		&i.Location,
		&i.Summary,
	)
	return i, err
}

const getEventMembership = `-- name: GetEventMembership :one
SELECT role FROM event_members 
WHERE event_id = $1 AND person_id = $2
`

type GetEventMembershipParams struct {
	EventID  uuid.UUID
	PersonID uuid.UUID
}

func (q *Queries) GetEventMembership(ctx context.Context, arg GetEventMembershipParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getEventMembership, arg.EventID, arg.PersonID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getEventTasks = `-- name: GetEventTasks :many
SELECT 
    t.id, t.title, t.description, t.owner_id, t.status, t.priority, t.due_date, t.tags, t.last_update_at, t.created_at, t.event_id, t.category, t.completed_at, t.is_archived, t.deleted_at, t.assignee_text, t.subtasks, 
    p.name as owner_name 
FROM tasks t
LEFT JOIN people p ON t.owner_id = p.id
WHERE t.event_id = $1 
AND t.deleted_at IS NULL
AND ($2::boolean = TRUE OR t.status != 'done')
ORDER BY 
    CASE WHEN t.status = 'done' THEN 1 ELSE 0 END,
    t.due_date ASC NULLS LAST
`

type GetEventTasksParams struct {
	EventID uuid.UUID
	Column2 bool
}

type GetEventTasksRow struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	OwnerID      uuid.NullUUID
	Status       string
	Priority     int32
	DueDate      sql.NullTime
	Tags         []string
	LastUpdateAt sql.NullTime
	CreatedAt    time.Time
	EventID      uuid.UUID
	Category     string
	CompletedAt  sql.NullTime
	IsArchived   bool
	DeletedAt    sql.NullTime
	AssigneeText sql.NullString
	Subtasks     pqtype.NullRawMessage
	OwnerName    sql.NullString
}

func (q *Queries) GetEventTasks(ctx context.Context, arg GetEventTasksParams) ([]GetEventTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getEventTasks, arg.EventID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEventTasksRow
	for rows.Next() {
		var i GetEventTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			pq.Array(&i.Tags),
			&i.LastUpdateAt,
			&i.CreatedAt,
			&i.EventID,
			&i.Category,
			&i.CompletedAt,
			&i.IsArchived,
			&i.DeletedAt,
			&i.AssigneeText,
			&i.Subtasks,
			&i.OwnerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGlobalActiveTasks = `-- name: GetGlobalActiveTasks :many
SELECT 
    t.id, t.title, t.description, t.owner_id, t.status, t.priority, t.due_date, t.tags, t.last_update_at, t.created_at, t.event_id, t.category, t.completed_at, t.is_archived, t.deleted_at, t.assignee_text, t.subtasks, 
    p.name as owner_name,
    e.name as event_name
FROM tasks t
LEFT JOIN people p ON t.owner_id = p.id
JOIN events e ON t.event_id = e.id
WHERE t.status != 'done' 
AND t.deleted_at IS NULL
ORDER BY t.priority DESC, t.due_date ASC
`

type GetGlobalActiveTasksRow struct {
	ID           uuid.UUID
	Title        string
	Description  sql.NullString
	OwnerID      uuid.NullUUID
	Status       string
	Priority     int32
	DueDate      sql.NullTime
	Tags         []string
	LastUpdateAt sql.NullTime
	CreatedAt    time.Time
	EventID      uuid.UUID
	Category     string
	CompletedAt  sql.NullTime
	IsArchived   bool
	DeletedAt    sql.NullTime
	AssigneeText sql.NullString
	Subtasks     pqtype.NullRawMessage
	OwnerName    sql.NullString
	EventName    string
}

func (q *Queries) GetGlobalActiveTasks(ctx context.Context) ([]GetGlobalActiveTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getGlobalActiveTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGlobalActiveTasksRow
	for rows.Next() {
		var i GetGlobalActiveTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			pq.Array(&i.Tags),
			&i.LastUpdateAt,
			&i.CreatedAt,
			&i.EventID,
			&i.Category,
			&i.CompletedAt,
			&i.IsArchived,
			&i.DeletedAt,
			&i.AssigneeText,
			&i.Subtasks,
			&i.OwnerName,
			&i.EventName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPerson = `-- name: GetPerson :one
SELECT id, name, role, created_at, email, password_hash FROM people WHERE id = $1
`

func (q *Queries) GetPerson(ctx context.Context, id uuid.UUID) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPerson, id)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getPersonByEmail = `-- name: GetPersonByEmail :one
SELECT id, name, role, created_at, email, password_hash FROM people WHERE email = $1
`

func (q *Queries) GetPersonByEmail(ctx context.Context, email sql.NullString) (Person, error) {
	row := q.db.QueryRowContext(ctx, getPersonByEmail, email)
	var i Person
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.Email,
		&i.PasswordHash,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, title, description, owner_id, status, priority, due_date, tags, last_update_at, created_at, event_id, category, completed_at, is_archived, deleted_at, assignee_text, subtasks FROM tasks WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		pq.Array(&i.Tags),
		&i.LastUpdateAt,
		&i.CreatedAt,
		&i.EventID,
		&i.Category,
		&i.CompletedAt,
		&i.IsArchived,
		&i.DeletedAt,
		&i.AssigneeText,
		&i.Subtasks,
	)
	return i, err
}

const getTaskEvents = `-- name: GetTaskEvents :many
SELECT id, task_id, event_type, changes, created_at, actor_id FROM task_events WHERE task_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetTaskEvents(ctx context.Context, taskID uuid.UUID) ([]TaskEvent, error) {
	rows, err := q.db.QueryContext(ctx, getTaskEvents, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskEvent
	for rows.Next() {
		var i TaskEvent
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.EventType,
			&i.Changes,
			&i.CreatedAt,
			&i.ActorID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksForFollowUp = `-- name: GetTasksForFollowUp :many
SELECT id, title, description, owner_id, status, priority, due_date, tags, last_update_at, created_at, event_id, category, completed_at, is_archived, deleted_at, assignee_text, subtasks FROM tasks 
WHERE status != 'done' 
AND deleted_at IS NULL
AND due_date IS NOT NULL 
AND assignee_text IS NOT NULL 
AND assignee_text != ''
`

func (q *Queries) GetTasksForFollowUp(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getTasksForFollowUp)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.OwnerID,
			&i.Status,
			&i.Priority,
			&i.DueDate,
			pq.Array(&i.Tags),
			&i.LastUpdateAt,
			&i.CreatedAt,
			&i.EventID,
			&i.Category,
			&i.CompletedAt,
			&i.IsArchived,
			&i.DeletedAt,
			&i.AssigneeText,
			&i.Subtasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTemplateTasks = `-- name: GetTemplateTasks :many
SELECT id, template_id, title, description, category, priority, relative_due_days FROM template_tasks WHERE template_id = $1
`

func (q *Queries) GetTemplateTasks(ctx context.Context, templateID uuid.UUID) ([]TemplateTask, error) {
	rows, err := q.db.QueryContext(ctx, getTemplateTasks, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateTask
	for rows.Next() {
		var i TemplateTask
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.Priority,
			&i.RelativeDueDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT 
    e.id, 
    e.name, 
    e.event_date,
    e.location,
    e.summary,
    COUNT(t.id) as total_tasks, 
    COUNT(t.id) FILTER (WHERE t.status = 'done' AND t.deleted_at IS NULL) as completed_tasks
FROM events e
LEFT JOIN tasks t ON e.id = t.event_id AND t.deleted_at IS NULL
GROUP BY e.id
ORDER BY e.event_date ASC
`

type ListEventsRow struct {
	ID             uuid.UUID
	Name           string
	EventDate      time.Time
	Location       sql.NullString
	Summary        sql.NullString
	TotalTasks     int64
	CompletedTasks int64
}

func (q *Queries) ListEvents(ctx context.Context) ([]ListEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsRow
	for rows.Next() {
		var i ListEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.Location,
			&i.Summary,
			&i.TotalTasks,
			&i.CompletedTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPeople = `-- name: ListPeople :many
SELECT id, name, role, created_at, email, password_hash FROM people ORDER BY name ASC
`

func (q *Queries) ListPeople(ctx context.Context) ([]Person, error) {
	rows, err := q.db.QueryContext(ctx, listPeople)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Person
	for rows.Next() {
		var i Person
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
			&i.Email,
			&i.PasswordHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTemplates = `-- name: ListTemplates :many
SELECT id, name, description, created_at FROM templates ORDER BY name ASC
`

func (q *Queries) ListTemplates(ctx context.Context) ([]Template, error) {
	rows, err := q.db.QueryContext(ctx, listTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Template
	for rows.Next() {
		var i Template
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEvents = `-- name: ListUserEvents :many
SELECT 
    e.id, e.name, e.event_date, e.location, e.summary,
    em.role as user_role,
    COUNT(t.id) as total_tasks, 
    COUNT(t.id) FILTER (WHERE t.status = 'done' AND t.deleted_at IS NULL) as completed_tasks
FROM events e
JOIN event_members em ON e.id = em.event_id
LEFT JOIN tasks t ON e.id = t.event_id AND t.deleted_at IS NULL
WHERE em.person_id = $1
GROUP BY e.id, em.role
ORDER BY e.event_date ASC
`

type ListUserEventsRow struct {
	ID             uuid.UUID
	Name           string
	EventDate      time.Time
	Location       sql.NullString
	Summary        sql.NullString
	UserRole       string
	TotalTasks     int64
	CompletedTasks int64
}

func (q *Queries) ListUserEvents(ctx context.Context, personID uuid.UUID) ([]ListUserEventsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserEvents, personID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserEventsRow
	for rows.Next() {
		var i ListUserEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EventDate,
			&i.Location,
			&i.Summary,
			&i.UserRole,
			&i.TotalTasks,
			&i.CompletedTasks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTask = `-- name: SoftDeleteTask :exec
UPDATE tasks 
SET deleted_at = NOW() 
WHERE id = $1
`

func (q *Queries) SoftDeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, softDeleteTask, id)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET 
    name = COALESCE($1, name),
    event_date = COALESCE($2, event_date),
    location = COALESCE($3, location),
    summary = COALESCE($4, summary)
WHERE id = $5
RETURNING id, name, event_date, created_at, location, summary
`

type UpdateEventParams struct {
	Name      sql.NullString
	EventDate sql.NullTime
	Location  sql.NullString
	Summary   sql.NullString
	ID        uuid.UUID
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Name,
		arg.EventDate,
		arg.Location,
		arg.Summary,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EventDate,
		&i.CreatedAt,
		&i.Location,
		&i.Summary,
	)
	return i, err
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET 
    title       = COALESCE($1, title),
    description = COALESCE($2, description),
    status      = COALESCE($3, status),
    priority    = COALESCE($4, priority),
    due_date    = COALESCE($5, due_date),
    category    = COALESCE($6, category),
    owner_id    = COALESCE($7, owner_id),
    assignee_text = COALESCE($8, assignee_text), -- Added
    subtasks    = COALESCE($9, subtasks),             -- Added
    last_update_at = NOW()
WHERE id = $10
RETURNING id, title, description, owner_id, status, priority, due_date, tags, last_update_at, created_at, event_id, category, completed_at, is_archived, deleted_at, assignee_text, subtasks
`

type UpdateTaskParams struct {
	Title        sql.NullString
	Description  sql.NullString
	Status       sql.NullString
	Priority     sql.NullInt32
	DueDate      sql.NullTime
	Category     sql.NullString
	OwnerID      uuid.NullUUID
	AssigneeText sql.NullString
	Subtasks     pqtype.NullRawMessage
	ID           uuid.UUID
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTask,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.DueDate,
		arg.Category,
		arg.OwnerID,
		arg.AssigneeText,
		arg.Subtasks,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.OwnerID,
		&i.Status,
		&i.Priority,
		&i.DueDate,
		pq.Array(&i.Tags),
		&i.LastUpdateAt,
		&i.CreatedAt,
		&i.EventID,
		&i.Category,
		&i.CompletedAt,
		&i.IsArchived,
		&i.DeletedAt,
		&i.AssigneeText,
		&i.Subtasks,
	)
	return i, err
}
